# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-aggregator
  template:
    metadata:
      labels:
        app: job-aggregator
    spec:
      containers:
      - name: job-aggregator
        image: job-aggregator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3031
        env:
        - name: REDEPLOY_TRIGGER
          value: "1" # Change this value to trigger redeploy

