apiVersion: v1
kind: Service
metadata:
  name: job-aggregator-service
spec:
  type: NodePort
  selector:
    app: job-aggregator
  ports:
    - protocol: TCP
      port: 3031
      targetPort: 3031
      nodePort: 30000

